field: 4438a5f8-cf85-40fb-9850-85c6dd3fa1b7 # Content Builder
fieldLayouts:
  65cb3b10-9718-49e7-bae4-fdd2574a0b69:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5c95439d-be69-4d70-af20-971744ad8855 # Visible
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8710811c-f673-4078-af87-e1f0d63a132d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: da582d2b-aecd-4155-9c79-c883619fa44b
        userCondition: null
fields:
  5c95439d-be69-4d70-af20-971744ad8855: # Visible
    columnSuffix: ulzthzmu
    contentColumnType: boolean
    fieldGroup: null
    handle: visible
    instructions: null
    name: Visible
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: divider
name: Divider
sortOrder: 2
