field: 4438a5f8-cf85-40fb-9850-85c6dd3fa1b7 # Content Builder
fieldLayouts:
  af9b6f4a-ccc5-403d-9271-9811b69a21b3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9dcda639-46c7-468a-a21d-5c683b6c1e04 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d87a010c-df22-4f8b-a877-fb62f3079e5b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7797e98a-8dbb-4e4e-be5f-1a8c035f395c # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98977b71-33b8-4c1d-90fb-44e0708375e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4c96a69a-cfb4-4227-8651-94d75c8bd93a # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 876137e4-a9f4-40f3-b2ae-29273f5d9d49
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b261e891-7f67-41f5-b6ea-1db11ea0f6f7 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df874bc1-c01e-434a-b443-3375e63d035d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 850dd26a-e1f4-464c-84d4-4a0ad4f124b3
        userCondition: null
fields:
  4c96a69a-cfb4-4227-8651-94d75c8bd93a: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:b3725018-b491-41b7-8a88-f36706c76d2f' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:b3725018-b491-41b7-8a88-f36706c76d2f' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  9dcda639-46c7-468a-a21d-5c683b6c1e04: # Headline
    columnSuffix: qvafrzrz
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7797e98a-8dbb-4e4e-be5f-1a8c035f395c: # Description
    columnSuffix: jhltdayp
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b261e891-7f67-41f5-b6ea-1db11ea0f6f7: # Subtitle
    columnSuffix: alaflloi
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: null
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: hero
name: Hero
sortOrder: 1
