fieldLayouts:
  87cc3d74-a23a-4f9b-a3a2-2cca2eeb2f60:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bc5dbbcb-d9a4-423b-bea1-3dd5f986386d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4438a5f8-cf85-40fb-9850-85c6dd3fa1b7 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d56ded61-a152-47d8-b1b4-167ac26fb892
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 69d773bc-8185-4fa2-a99d-200355515b79
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 060a0464-b9c6-4a45-a199-a5a2658ad8c8 # Blog Post
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
