fieldLayouts:
  1d067fd7-1998-498f-969f-6d862b58fa29:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: df9a27f6-fe37-4a3a-b5e1-e9e288b0a805
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05af2ac1-24f4-4e36-a7e8-b94f847a1568
        userCondition: null
fs: localFiles
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: localFiles
transformSubpath: ''
