defaultPlacement: end
enableVersioning: true
handle: blogPost
name: 'Blog Post'
propagationMethod: all
siteSettings:
  2fa19ba7-a1ec-4f24-8c27-f5641b6fca9b: # Craft 4 Plugins Dev
    enabledByDefault: true
    hasUrls: true
    template: blog-post/_entry
    uriFormat: 'blog-post/{slug}'
type: channel
